#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use Perl6::Slurp;

# We have an SSH key set up to provide access.
my @ssh = qw/ssh -T -o PasswordAuthentication=false -l betterge 
             -p 45667 fhiso.org/;

my $path = 'domains/fhiso.org/public_html/.htaccess';

open my $fh, "|-", @ssh, "cat > $path.new";
print $fh <<EOF;
# ***********************************************************************
# ***   This file is automatically generated.   Edits will be lost.   ***
# *                                                                     *
# * To update it, edit the version in the 'website' Github repostitory. *
# * The tech server overwrites this file hourly from git.               *
# ***********************************************************************

EOF
print $fh slurp "$FindBin::Bin/htaccess";
print $fh "\n# Updated at ".`TZ=UTC date`."\n";
close $fh or die;

# Move it into place
system @ssh, 'mv', "$path.new", $path;

