#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use Perl6::Slurp;
use String::ShellQuote;

my @ssh_opts = qw/-o PasswordAuthentication=false/;
my $ssh_user = 'betterge';
my $ssh_port = 45667;
my $ssh_host = 'fhiso.org';
my $remote_dir = 'domains/fhiso.org/public_html';

# We have an SSH key set up to provide access.
my @ssh = ('ssh', '-T', @ssh_opts, '-l', $ssh_user, '-p', $ssh_port, $ssh_host);

my $path = "$remote_dir/.htaccess";
open my $fh, "|-", @ssh, "cat > $path.new";
print $fh <<EOF;
# ***********************************************************************
# ***   This file is automatically generated.   Edits will be lost.   ***
# *                                                                     *
# * To update it, edit the version in the 'website' Github repostitory. *
# * The tech server overwrites this file hourly from git.               *
# ***********************************************************************

EOF
print $fh slurp "$FindBin::Bin/htaccess";
print $fh "\n# Updated at ".`TZ=UTC date`."\n";
close $fh or die;

# Move it into place
system @ssh, 'mv', "$path.new", $path;

# The www-upload directory just contains blank files.  Use it to get a 
# list of file names which we're going to fetch from the www/board/ 
# directory.  
my @pdfs = glob "$FindBin::Bin/../../www-upload/*.pdf";
s!.*/www-upload/!! foreach @pdfs;
chdir "$FindBin::Bin/../../www/board/";

# We want to rsync these files to the server, but Simply Hosting doesn't
# make rsync available on their shell accounts.  This does nothing to stop
# transmitting all the data across the internet each time, but it does 
# preserve mtimes (hence the -p option to tar).
system 'tar cz '.shell_quote(@pdfs) . ' | ' . shell_quote(@ssh) . ' ' .
 shell_quote(qw/tar xzp -C/, "$remote_dir/files/governance/");

